# Generated by Django 4.1.6 on 2023-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='content',
            field=models.TextField(blank=True, help_text='Заполните контентом', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(help_text='Вставьте фото', upload_to='photos/%Y/%m/%d', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнеее изменения'),
        ),
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=255, verbose_name='Заголовок'),
        ),
    ]
